### ISSUE TITLE
Is SMAPIv3 still maintained?

### ISSUE THREAD

**Issue by olivierlambert** [xapi-project/xapi-storage#101]
Hello there!

Just asking if SMAPIv3 (or v5 now?) is still actively developped because there isn't a lot of activity here (plus `qemu-dp` dev is done behind closed doors, so it's hard to tell).

If we (XCP-ng team) can help on anything, let us know :)

**Comment by gaborigloi** [comment]
Hi!

Yes, it is maintained. We just didn't need to make changes in this area recently.

Thank you very much for offering help, we will let you know, but currently I can't think of anything that needs to be done.

**Comment by olivierlambert** [comment]
Ah good news then! Thank you for your answer :+1:
