### ISSUE TITLE
Possibility to pass a raw device?

### ISSUE THREAD

**Issue by olivierlambert** [xapi-project/xapi-storage#103]
Is it possible to pass/attach a raw device (eg a whole disk? or any block device) directly to a VM?

If yes, what would be the best way to do so?

**Comment by MarkSymsCtx** [comment]
Use blkback. Implementation of datapaths is an exercise for the implementer. Some of the example code in this archived repository might be informative. https://github.com/xapi-project/xapi-storage-plugins/tree/master/datapath.

This repository just contains the API definitions.

**Comment by olivierlambert** [comment]
Thanks, I'll take a look there 👍

**Comment by gaborigloi** [comment]
https://github.com/xapi-project/xapi-storage/pull/105 added an up to date example datapath implementation that should be a good starting point for this

**Comment by olivierlambert** [comment]
Thanks a lot!
