### ISSUE TITLE
Unclear relationship between URI and device_config

### ISSUE THREAD

**Issue by djs55** [xapi-project/xapi-storage#11]
Currently we have

```
SR.create sr uri configuration
SR.attach sr uri
```

and we have per-host "device_config".

Proposal:
1. set the URI = "device_config:uri"
2. pass the device_config as 'configuration' (minus 'uri' and 'SRmaster'?)

The documentation should be that 'configuration is passed at create-time only because it affects the creation of the SR. Once an SR is created the configuration is self-evident. To refer to an existing SR, the URI is always sufficient'

**Comment by gaborigloi** [comment]
The interface has been changed and now attach takes a configuration.
