### ISSUE TITLE
Should datapath.attach return multiple uris?

### ISSUE THREAD

**Issue by djs55** [xapi-project/xapi-storage#24]
In particular if I have a .qcow file, I would probably prefer to use Qemu qdisk to serve it up. If I would like to import data in dom0, I need to fall back to a block device.

Alternatively: the tool in dom0 which needs the block device could run the block attach plugin?

Alternatively: we could ban blkfront's in dom0 (but this causes problems with suspend/resume and pygrub on file SRs)

**Comment by gaborigloi** [comment]
Now we return a list of things from Datapath.attach: https://xapi-project.github.io/xapi-storage/#datapath-method-attach
