### ISSUE TITLE
Development schedule

### ISSUE THREAD

**Issue by al-sharp** [xapi-project/xapi-storage#25]
Has been quiet for a while.  Any chance this project will be resuming active development soon?

**Comment by djs55** [comment]
Hi,

Most of the active development is on the example implementations of this
interface, in particular

- https://github.com/xapi-project/ezlvm
- https://github.com/xapi-project/ffs

My plan is to implement more features in those and figure out which bits of
API are missing and feed the results back here.



On Thu, Feb 12, 2015 at 6:46 PM, Steve Harp <notifications@github.com>
wrote:

> Has been quiet for a while. Any chance this project will be resuming
> active development soon?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/djs55/xapi-storage/issues/25>.
>



-- 
Dave Scott

**Comment by djs55** [comment]
Note that development on ffs is quite active again, and I'm working on this repo too.

**Comment by gaborigloi** [comment]
This project is still maintained
