### ISSUE TITLE
SR.attach probably needs configuration

### ISSUE THREAD

**Issue by djs55** [xapi-project/xapi-storage#34]
The URI is always _input_ to the SR.create/SR.attach so it can't be modified to include configuration. If configuration is passed on SR.create, it may not be possible to write it to the storage to be read by the attach. Additionally we would allow the user to unplug the storage and supply a different configuration.

**Comment by gaborigloi** [comment]
SR.attach now takes a configuration: https://github.com/xapi-project/xapi-storage/blob/master/generator/lib/control.ml#L393
