### ISSUE TITLE
Dundee xapi-storage question

### ISSUE THREAD

**Issue by sand7000** [xapi-project/xapi-storage#59]
Dundee (Beta) question:  I'm interested in running a storage driver (SR)
in a domain other than dom0.  In previous versions of XenServer, this
has been possible (with blktap2 and some SMAPIv2 code) via configuring:

xe pbd-param-set uuid=$PBD other-config:storage_driver_domain=<driver
domain uuid>

but this does not seem to be the case in Dundee.  I read here:

http://djs55.github.io/xapi-storage/datapath.html

that the datapath plugin takes a URI which points to virtual disk data
and chooses a Xen datapath implementation: driver domain, blkback
implementation and caching strategy.  If I am reading this correctly a
properly formatted URI will allow disaggregated storage by specifying a
storage driver domain.  Is this functionality currently implemented and
if so can I have a hint on how it would be accomplished?

**Comment by gaborigloi** [comment]
This functionality has not been implemented yet.
