### ISSUE TITLE
SMAPIv3 performance

### ISSUE THREAD

**Issue by olivierlambert** [xapi-project/xapi-storage#91]
As suggested by @kc284 , I post here for better/more fluid discussion regarding storage stack :+1: (thanks god I prefer GitHub than Jira!)

Since `GFS2` started to use `SMAPIv3` and `qcow2` file format, we decided to do some performance tests.

In order to keep it simple as possible, only the filelevel based SR is tested:
```
xe sr-create type=filebased name-label=test-filebased device-config:file-uri=file:///mnt/ssd
```

Few minor issues: name-label and name-description aren't pushed correctly to XAPI, the SR is named "SR NAME" with "FILEBASED SR" decription. It's only a small glitch, but at least it's reported Otherwise, I can confirm the disk file is created and is a valid `qcow2` file.

I did a benchmark on a Samsung 850 EVO SSD, on the same VM. Before benching, I did a local 'ext' SR on the same disk and still the same VM, so I could compare it.

Here is the results:

* Sequential booth read then write (queue depth 32, 1 thread): `SMAPIv3` is **3 times slower** than "ext" SR. Also with SMAPIv3, note that `tapdisk` process seems to be at 100%.
* Random Read (4KiB, queue depth 8, 8 threads): `SMAPIv3` is **150 times slower** than "ext" SR
* Random Write (4KiB, queue depth 8, 8 threads): `SMAPIv3` is **95 times slower** than "ext" SR

If you want the detailed numbers, let me know.

Did I missed something during the SR creation? Since `GFS2` is basically filelevel + `GFS2` FS + cluster on top, I should expect roughly the same result I suppose.

**Comment by olivierlambert** [comment]
Result on the Windows 2012 R2 VMs, using the Samsung 850 EVO:

### `ext` file based SR

![filelevelssdlegacy](https://user-images.githubusercontent.com/1241401/44199222-cda7b100-a143-11e8-8eb8-810d033d7782.png)


### `SMAPIv3` filebased

![filelevessdng](https://user-images.githubusercontent.com/1241401/44199212-c8e2fd00-a143-11e8-80ed-88f8644f11d9.png)

**Comment by MarkSymsCtx** [comment]
The issue here was nothing to do with how the SR was managed but purely a bug in qemu, since fixed.

**Comment by olivierlambert** [comment]
Great! Can you point me where I can find the fix? I'd like to re-run some test with the fix then :+1:

**Comment by MarkSymsCtx** [comment]
You can't, it will be release in a future version of xenserver

**Comment by olivierlambert** [comment]
What do you mean? There is no public repo where the fix is? :fearful:

**Comment by MarkSymsCtx** [comment]
correct, still awaiting review by the upstream qemu  maintainers

**Comment by olivierlambert** [comment]
Is there a public PR against upstream Qemu then?

**Comment by olivierlambert** [comment]
I'm trying to search on the qemu-devel mailing list, but if you have a clue on the subject or the email that posted the patch, that would be really helpful :+1: 

Thanks!

**Comment by olivierlambert** [comment]
@MarkSymsCtx I'm struggling to find the relevant patches on QEMU-devel. I have some potential matches but it's hard to tell, mainly because I don't know which file was modified or who pushed the patch on the mailing list.

Here the list of Citrix people who posted on this list since April:

* Roger Pau Monné
* Paul Durrant
* Weil Liu
* Anthony Perard
* Ian Jackson
* Igor Druzhinin

I think I've read all those patches/description without spotting anything related to this disk speed problem.

**Comment by MarkSymsCtx** [comment]
It's probably gone internally as I believe the upstream maintainer for that part is also an employee or it's still undergoing internal review, all I know for sure is it's fixed.

**Comment by olivierlambert** [comment]
Thanks for your answer Mark :+1: Let me try to recap the situation and tell me if it's correct or if I missed something:

1. Citrix got an internal fork of Open Source `qemu`, but it's not public
1. Some patches are made inside this private repo, then go public in QEMU-devel when you want to have the patch merged Qemu upstream

**Comment by MarkSymsCtx** [comment]
Correct

**Comment by olivierlambert** [comment]
up @MarkSymsCtx :wink:

**Comment by olivierlambert** [comment]
So I did new tests, and it's really good (for file level SR):

* more than **+100%** in random write speed with (queue 8 and 8 threads, same with queue 32 and 1 thread)
* but between -10% and -20% perfs with queue 1 and 1 thread, maybe not a big deal, but I suppose giving you feedback is not bad @MarkSymsCtx :wink: 

Also tested `nfs-ng`, sadly performance are catastrophic on this side. Is it expected?

**Comment by MarkSymsCtx** [comment]
Nfs-ng is not supported or maintained and should not have been shipped, it was rough prototype code for validating the API operations, surprised it still works at all at any level of performance.

**Comment by olivierlambert** [comment]
Well, in fact, file based SR on top of an NFS mount shows the exact same perf issue (and no problem with local disk). So I suppose it's somehow related on `qemu-dp` works and network latency isn't really good for it. But that's just an assumption based on the numbers I got. Is there anything we could tweak (cache or something like that) that could help on this?
